## Goal - Create reproducible training and validation datasets.

Output:
    X_train,
    X_val,
    y_train,
    y_val

No preprocessing is performed in this notebook.

In [1]:
# Required Imports
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
# Loading the data
train_df = pd.read_csv("../data/raw/train.csv")
test_df = pd.read_csv("../data/raw/test.csv")

In [3]:
# Splitting into features X and label y
X = train_df.drop("Survived", axis=1)
y = train_df["Survived"]

In [4]:
# Train/Validation Split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [5]:
print(X_train.shape)
print(X_val.shape)
print(y_train.shape)
print(y_val.shape)

(712, 11)
(179, 11)
(712,)
(179,)

In [6]:
## Checking Class Imbalance
y_train.value_counts(normalize=True)

Survived
0    0.616573
1    0.383427
Name: proportion, dtype: float64

In [7]:
y_val.value_counts(normalize=True)

Survived
0    0.614525
1    0.385475
Name: proportion, dtype: float64

# Production Feature Engineering

In this section, we validate the production implementation of our custom feature engineering transformers.

In [8]:
from titanic_survival.features.engineering import TitleExtractor

In [9]:
title_extractor = TitleExtractor()

In [10]:
X_train_title = title_extractor.fit_transform(X_train)
X_val_title = title_extractor.fit_transform(X_val)

In [11]:
X_train_title[["Name", "Title"]].head(10)

                                                  Name Title
692                                       Lam, Mr. Ali    Mr
481                   Frost, Mr. Anthony Wood "Archie"    Mr
527                                 Farthing, Mr. John    Mr
855                         Aks, Mrs. Sam (Leah Rosen)   Mrs
801        Collyer, Mrs. Harvey (Charlotte Annie Tate)   Mrs
652                     Kalvik, Mr. Johannes Halvorsen    Mr
509                                     Lang, Mr. Fang    Mr
557                                Robbins, Mr. Victor    Mr
828                       McCormack, Mr. Thomas Joseph    Mr
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...   Mrs

In [12]:
X_train_title["Title"].value_counts()

Title
Mr          412
Miss        141
Mrs         107
Master       31
Dr            6
Rev           5
Col           2
Mlle          2
Major         1
Lady          1
Sir           1
Ms            1
Jonkheer      1
Don           1
Name: count, dtype: int64

In [13]:
X_val_title[["Name", "Title"]].head(10)

                                             Name  Title
565                          Davies, Mr. Alfred J     Mr
160                      Cribb, Mr. John Hatfield     Mr
553             Leeni, Mr. Fahim ("Philip Zenni")     Mr
860                       Hansen, Mr. Claus Peter     Mr
241                Murphy, Miss. Katherine "Kate"   Miss
559  de Messemaeker, Mrs. Guillaume Joseph (Emma)    Mrs
387                              Buss, Miss. Kate   Miss
536             Butt, Major. Archibald Willingham  Major
698                      Thayer, Mr. John Borland     Mr
99                              Kantor, Mr. Sinai     Mr

In [14]:
X_val_title["Title"].value_counts()

Title
Mr              105
Miss             41
Mrs              18
Master            9
Major             1
Mme               1
Capt              1
the Countess      1
Dr                1
Rev               1
Name: count, dtype: int64